apiVersion: apps/v1
kind: Deployment
metadata:
  name: lambserver
spec:
  selector:
    matchLabels:
      app: lambserver
  replicas: 1
  template:
    metadata:
      labels:
        app: lambserver
    spec:
      serviceAccountName: lambserver-account
      volumes:
        - name: lambserver-persistent-storage
          persistentVolumeClaim:
            claimName: lambserver-volumeclaim
      containers:
        - name: lambserver-container
          image: sundarigari/lambserver:v17
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              #name: lambserver-port
          volumeMounts:
            - name: lambserver-persistent-storage
              mountPath: /logs
