apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-volume2
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
  hostPath:
    path: /tmp
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-volumeclaim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      name: redis-volume2
