apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol2
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
  hostPath:
    path: /temp/data
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: lambserver-volumeclaim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
