apiVersion: v1
kind: Service
metadata:
  labels:
    app: lambserver
  name: lambserver-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: lambserver