apiVersion: v1
kind: Service
metadata:
  labels:
    app: lambserver
  name: lambserver-lb90
spec:
  type: LoadBalancer
  ports:
  - port: 90
    targetPort: 90
    protocol: TCP
  selector:
    app: lambserver